force-app/main/default/objects/Card__c/Card__c.object-meta.xml
<CustomObject>
    <label>Card</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Card__c/fields/Assignee__c.field-meta.xml
<CustomField>
    <fullName>Assignee__c</fullName>
    <label>Assignee</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Card__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Card__c/fields/StatusPosition__c.field-meta.xml
<CustomField>
    <fullName>StatusPosition__c</fullName>
    <label>StatusPosition</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/KanbanBoardController.cls
public with sharing class KanbanBoardController {

    @AuraEnabled
    public static KanbanBoard getKanbanBoard() {
        TrelloSyncController.syncCards();

        Set<String> statuses = new Set<String>();
        List<Integer> statusPosition = new List<Integer>();
        List<Card__c> availableCardList = [
            SELECT Name, Description__c, Assignee__c, Due_Date__c, Status__c, Status_Id__c, StatusPosition__c
            FROM Card__c
            ORDER BY StatusPosition__c
        ];

        for (Card__c card : availableCardList) {
            statuses.add(card.Status__c);
            statusPosition.add((Integer) card.StatusPosition__c);
        }

        return new KanbanBoard(availableCardList, new List<String>(statuses), statusPosition);
    }

    @AuraEnabled
    public static String getUpdateStatus(Id recordId, String status, Integer position) {
        SObject card = recordId.getSObjectType().newSObject(recordId);
        card.put('Status__c', status);
        card.put('StatusPosition__c', position);

        update card;

        return 'Success';
    }

    public class KanbanBoard {
        @AuraEnabled
        public List<Card__c> cardList { get; set; }
        @AuraEnabled
        public List<String> statusList { get; set; }
        @AuraEnabled
        public List<Integer> statusPosition { get; set; }

        public KanbanBoard (List<Card__c> cards, List<String> statuses, List<Integer> positions) {
            this.cardList = cards;
            this.statusList = statuses;
            this.statusPosition = positions;
        }
    }
}