force-app/main/default/objects/Card__c/Card__c.object-meta.xml
<CustomObject>
    <label>Card</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Card__c/fields/Assignee__c.field-meta.xml
<CustomField>
    <fullName>Assignee__c</fullName>
    <label>Assignee</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Card__c/fields/Card_Id__c.field-meta.xml
<CustomField>
    <fullName>Card_Id__c</fullName>
    <externalId>true</externalId>
    <label>Card Id</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Card__c/fields/Card_Position__c.field-meta.xml
<CustomField>
    <fullName>Card_Position__c</fullName>
    <label>Card Position</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Card__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TrelloSettings__c/TrelloSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Trello Settings</label>
</CustomObject>

force-app/main/default/objects/TrelloSettings__c/fields/Api_key__c.field-meta.xml
<CustomField>
    <fullName>Api_key__c</fullName>
    <label>Api key</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TrelloSettings__c/fields/Board_Name__c.field-meta.xml
<CustomField>
    <fullName>Board_Name__c</fullName>
    <label>Board Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TrelloSettings__c/fields/Board_URL__c.field-meta.xml
<CustomField>
    <fullName>Board_URL__c</fullName>
    <label>Board URL</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/TrelloSettings__c/fields/Sync_Date__c.field-meta.xml
<CustomField>
    <fullName>Sync_Date__c</fullName>
    <label>Sync Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/TrelloSettings__c/fields/Trello_Sync_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Trello_Sync_Endpoint__c</fullName>
    <label>Trello Sync Endpoint</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TrelloSettings__c/fields/User_Name__c.field-meta.xml
<CustomField>
    <fullName>User_Name__c</fullName>
    <label>User Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/KanbanBoardControllerTest.cls
@isTest
private class KanbanBoardControllerTest {

    @testSetup
    private static void setupTestData() {
        TrelloSettings__c newTrelloSettings = new TrelloSettings__c(
            Api_key__c = 'testApiKey',
            Board_Name__c = 'testBoardName',
            Board_URL__c = 'https://test.com/testBoardName',
            Token__c = 'testToken',
            User_Name__c = 'TestUser',
            Trello_Sync_Endpoint__c = 'https://api.trello.com/1/{0}/{1}/{2}?key={3}&token={4}'
        );

        insert newTrelloSettings;

        Card__c newCard = new Card__c(
            Card_Id__c = 'cardId',
            Name = 'cardName',
            Description__c = 'cardDescription',
            Assignee__c = 'TestUser',
            Status__c = 'TO DO',
            Card_Position__c = '0'
        );

        insert newCard;

        System.assertNotEquals(null, newTrelloSettings.Id, 'Record is not created');
        System.assertNotEquals(null, newCard.Id, 'Record is not created');
    }

    @isTest
    private static void testGetTrelloCards() {

        TrelloSettings__c trelloSettings = TrelloSettings__c.getInstance();
        List<String> endPointList = new List<String> {
            String.format(trelloSettings.Trello_Sync_Endpoint__c, new List<String> {
                'members',
                trelloSettings.User_Name__c,
                'boards',
                trelloSettings.Api_key__c,
                trelloSettings.Token__c
            }),
            String.format(trelloSettings.Trello_Sync_Endpoint__c, new List<String> {
                'boards',
                'boardId',
                'lists',
                trelloSettings.Api_key__c,
                trelloSettings.Token__c
            }),
            String.format(trelloSettings.Trello_Sync_Endpoint__c, new List<String> {
                'boards',
                'boardId',
                'members',
                trelloSettings.Api_key__c,
                trelloSettings.Token__c
            }),
            String.format(trelloSettings.Trello_Sync_Endpoint__c, new List<String> {
                'boards',
                'boardId',
                'cards',
                trelloSettings.Api_key__c,
                trelloSettings.Token__c
            })
        };

        Test.setMock(HttpCalloutMock.class, new TrelloSyncCalloutMock(endPointList));
        Test.startTest();

        KanbanBoardController.getSync();

        Test.stopTest();

        TrelloSettings__c updatedTrelloSettings = TrelloSettings__c.getInstance();

        System.assertEquals(
            System.now().format('MM/dd/yyyy HH:mm'),
            updatedTrelloSettings.Sync_Date__c.format('MM/dd/yyyy HH:mm'),
            'Sync failed'
        );
    }

    @isTest
    private static void testGetKanbanBoard() {

        Test.startTest();

        KanbanBoardController.KanbanBoard kanbanBoard = KanbanBoardController.getKanbanBoard();

        Test.stopTest();

        List<Card__c> actualCardList = [
            SELECT Name, Description__c, Assignee__c, Status__c, Card_Position__c, Card_Id__c
            FROM Card__c
        ];

        System.assertEquals(kanbanBoard.cardList, actualCardList, 'Kanban Board data is not received');
    }

    @isTest
    private static void testUpdateStatus() {
        String status = 'UAT';
        List<Card__c> cardList = [
            SELECT Id
            FROM Card__c
        ];

        List<String> cardIds = new List<String>(new Map<String, Card__c>(cardList).keySet());

        Test.startTest();

        KanbanBoardController.getUpdateStatus(status, cardIds);

        Test.stopTest();

        List<Card__c> actualCardList = [
            SELECT Status__c, Card_Position__c
            FROM Card__c
            WHERE Status__c = :status
                AND Id IN :cardIds
        ];

        System.assertEquals(false, actualCardList.isEmpty(), 'Card data is not updated');
    }
}