force-app/main/default/objects/Card__c/Card__c.object-meta.xml
<CustomObject>
    <label>Card</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TrelloSettings__c/TrelloSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Trello Settings</label>
</CustomObject>

force-app/main/default/objects/TrelloSettings__c/fields/Api_key__c.field-meta.xml
<CustomField>
    <fullName>Api_key__c</fullName>
    <label>Api key</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TrelloSettings__c/fields/Board_Name__c.field-meta.xml
<CustomField>
    <fullName>Board_Name__c</fullName>
    <label>Board Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TrelloSettings__c/fields/Board_URL__c.field-meta.xml
<CustomField>
    <fullName>Board_URL__c</fullName>
    <label>Board URL</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/TrelloSettings__c/fields/Sync_Date__c.field-meta.xml
<CustomField>
    <fullName>Sync_Date__c</fullName>
    <label>Sync Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/TrelloSettings__c/fields/User_Name__c.field-meta.xml
<CustomField>
    <fullName>User_Name__c</fullName>
    <label>User Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TrelloSyncControllerTest.cls
@isTest
private class TrelloSyncControllerTest {

    @testSetup
    private static void setupTestData() {

        TrelloSettings__c trelloSettings = new TrelloSettings__c(
            Api_key__c = 'testApiKey',
            Board_Name__c = 'testBoardName',
            Board_URL__c = 'https://test.com/testBoardName',
            Token__c = 'testToken',
            User_Name__c = 'TestUser'
        );

        insert trelloSettings;

        System.assertNotEquals(null, trelloSettings.Id, 'Record is not created');
    }

    @isTest
    private static void testGetTrelloCards() {

        Test.setMock(HttpCalloutMock.class, new TrelloSyncCalloutMock());
        Test.startTest();

        TrelloSyncController.syncCards();

        Test.stopTest();

        Card__c card = [
            SELECT Id
            FROM Card__c
            LIMIT 1
        ];

        TrelloSettings__c trelloSettings = TrelloSettings__c.getOrgDefaults();

        System.assertNotEquals(null, card.id, 'Card is not created');
        System.assertEquals(System.now(), trelloSettings.Sync_Date__c, 'Sync Date is not updated');
    }
}