force-app/main/default/objects/Trello_Status_Setting__mdt/Trello_Status_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Trello Status Setting</label>
    <pluralLabel>Trello Status Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Trello_Status_Setting__mdt/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Trello_Status_Setting__mdt/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TrelloStatusSetting.cls
public with sharing class TrelloStatusSetting {

    public static List<Trello_Status_Setting__mdt> getTrelloStatusSetting() {
        List<Trello_Status_Setting__mdt> trelloStatusSettingList = new List<Trello_Status_Setting__mdt>();

        if (!Test.isRunningTest()) {
            trelloStatusSettingList = [
                SELECT Position__c, Status__c
                FROM Trello_Status_Setting__mdt
                ORDER BY Position__c
            ];
        } else {
            trelloStatusSettingList = new List<Trello_Status_Setting__mdt> {
                new Trello_Status_Setting__mdt(
                    Status__c = 'TO DO',
                    Position__c = 0
                ),
                new Trello_Status_Setting__mdt(
                    Status__c = 'In Progress',
                    Position__c = 1
                ),
                new Trello_Status_Setting__mdt(
                    Status__c = 'UAT',
                    Position__c = 2
                ),
                new Trello_Status_Setting__mdt(
                    Status__c = 'Done',
                    Position__c = 3
                )
            };
        }

        return trelloStatusSettingList;
    }
}